# Generated by Django 5.0.3 on 2024-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdir', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TubeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
