# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QSlider, QStatusBar, QTabWidget,
    QTableView, QTextBrowser, QToolButton, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1123, 650)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.playSlider = QSlider(self.centralwidget)
        self.playSlider.setObjectName(u"playSlider")
        self.playSlider.setGeometry(QRect(40, 540, 721, 20))
        self.playSlider.setOrientation(Qt.Horizontal)
        self.btn_region_reset = QPushButton(self.centralwidget)
        self.btn_region_reset.setObjectName(u"btn_region_reset")
        self.btn_region_reset.setGeometry(QRect(100, 580, 111, 31))
        self.btn_fileopen = QPushButton(self.centralwidget)
        self.btn_fileopen.setObjectName(u"btn_fileopen")
        self.btn_fileopen.setGeometry(QRect(680, 580, 81, 31))
        self.btn_play = QToolButton(self.centralwidget)
        self.btn_play.setObjectName(u"btn_play")
        self.btn_play.setGeometry(QRect(40, 580, 41, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 40, 720, 480))
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QFrame.WinPanel)
        self.playTimer = QLabel(self.centralwidget)
        self.playTimer.setObjectName(u"playTimer")
        self.playTimer.setGeometry(QRect(710, 560, 64, 15))
        self.btn_init_detection = QPushButton(self.centralwidget)
        self.btn_init_detection.setObjectName(u"btn_init_detection")
        self.btn_init_detection.setGeometry(QRect(230, 580, 131, 31))
        self.btn_page_print = QPushButton(self.centralwidget)
        self.btn_page_print.setObjectName(u"btn_page_print")
        self.btn_page_print.setGeometry(QRect(550, 580, 111, 31))
        self.label_fps = QLabel(self.centralwidget)
        self.label_fps.setObjectName(u"label_fps")
        self.label_fps.setGeometry(QRect(790, 590, 299, 20))
        self.label_roi = QLabel(self.centralwidget)
        self.label_roi.setObjectName(u"label_roi")
        self.label_roi.setGeometry(QRect(790, 560, 299, 21))
        self.label_xy = QLabel(self.centralwidget)
        self.label_xy.setObjectName(u"label_xy")
        self.label_xy.setGeometry(QRect(790, 530, 299, 20))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(780, 10, 331, 511))
        self.tab_control = QWidget()
        self.tab_control.setObjectName(u"tab_control")
        self.dropdown_models = QComboBox(self.tab_control)
        self.dropdown_models.setObjectName(u"dropdown_models")
        self.dropdown_models.setGeometry(QRect(60, 10, 231, 31))
        self.label_model = QLabel(self.tab_control)
        self.label_model.setObjectName(u"label_model")
        self.label_model.setGeometry(QRect(10, 9, 64, 31))
        font = QFont()
        font.setPointSize(12)
        self.label_model.setFont(font)
        self.checkbox_move = QCheckBox(self.tab_control)
        self.checkbox_move.setObjectName(u"checkbox_move")
        self.checkbox_move.setGeometry(QRect(10, 60, 211, 19))
        self.checkbox_move.setChecked(True)
        self.checkbox_yolo = QCheckBox(self.tab_control)
        self.checkbox_yolo.setObjectName(u"checkbox_yolo")
        self.checkbox_yolo.setGeometry(QRect(10, 80, 211, 19))
        self.checkbox_yolo.setChecked(False)
        self.label_3 = QLabel(self.tab_control)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 210, 111, 16))
        self.label_thr_yolo = QLabel(self.tab_control)
        self.label_thr_yolo.setObjectName(u"label_thr_yolo")
        self.label_thr_yolo.setGeometry(QRect(260, 150, 31, 16))
        self.label_thr_yolo.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_bright = QLabel(self.tab_control)
        self.label_bright.setObjectName(u"label_bright")
        self.label_bright.setGeometry(QRect(260, 180, 31, 16))
        self.label_bright.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.tab_control)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 180, 61, 16))
        self.thrSlider_yolo = QSlider(self.tab_control)
        self.thrSlider_yolo.setObjectName(u"thrSlider_yolo")
        self.thrSlider_yolo.setGeometry(QRect(90, 150, 160, 22))
        self.thrSlider_yolo.setMinimum(1)
        self.thrSlider_yolo.setSliderPosition(5)
        self.thrSlider_yolo.setOrientation(Qt.Horizontal)
        self.thrSlider_move = QSlider(self.tab_control)
        self.thrSlider_move.setObjectName(u"thrSlider_move")
        self.thrSlider_move.setGeometry(QRect(90, 120, 160, 22))
        self.thrSlider_move.setMinimum(1)
        self.thrSlider_move.setSliderPosition(5)
        self.thrSlider_move.setOrientation(Qt.Horizontal)
        self.label_0 = QLabel(self.tab_control)
        self.label_0.setObjectName(u"label_0")
        self.label_0.setGeometry(QRect(10, 120, 64, 15))
        self.label_thr_move = QLabel(self.tab_control)
        self.label_thr_move.setObjectName(u"label_thr_move")
        self.label_thr_move.setGeometry(QRect(260, 120, 31, 16))
        self.label_thr_move.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Slider_bright = QSlider(self.tab_control)
        self.Slider_bright.setObjectName(u"Slider_bright")
        self.Slider_bright.setGeometry(QRect(90, 180, 160, 22))
        self.Slider_bright.setMinimum(-50)
        self.Slider_bright.setMaximum(50)
        self.Slider_bright.setSliderPosition(0)
        self.Slider_bright.setOrientation(Qt.Horizontal)
        self.jump_frameSlider = QSlider(self.tab_control)
        self.jump_frameSlider.setObjectName(u"jump_frameSlider")
        self.jump_frameSlider.setGeometry(QRect(90, 210, 160, 22))
        self.jump_frameSlider.setMinimum(1)
        self.jump_frameSlider.setMaximum(50)
        self.jump_frameSlider.setValue(1)
        self.jump_frameSlider.setSliderPosition(1)
        self.jump_frameSlider.setOrientation(Qt.Horizontal)
        self.label_1 = QLabel(self.tab_control)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(10, 150, 64, 15))
        self.label_frame_gap = QLabel(self.tab_control)
        self.label_frame_gap.setObjectName(u"label_frame_gap")
        self.label_frame_gap.setGeometry(QRect(260, 210, 31, 16))
        self.label_frame_gap.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frame_option = QFrame(self.tab_control)
        self.frame_option.setObjectName(u"frame_option")
        self.frame_option.setGeometry(QRect(10, 240, 311, 231))
        self.frame_option.setFrameShape(QFrame.StyledPanel)
        self.frame_option.setFrameShadow(QFrame.Raised)
        self.tabWidget.addTab(self.tab_control, "")
        self.tab_multi = QWidget()
        self.tab_multi.setObjectName(u"tab_multi")
        self.verticalLayoutWidget_3 = QWidget(self.tab_multi)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(20, 60, 291, 401))
        self.vLayout_dongzip_statusbar = QVBoxLayout(self.verticalLayoutWidget_3)
        self.vLayout_dongzip_statusbar.setObjectName(u"vLayout_dongzip_statusbar")
        self.vLayout_dongzip_statusbar.setContentsMargins(0, 0, 0, 0)
        self.btn_dongzip_reset = QPushButton(self.tab_multi)
        self.btn_dongzip_reset.setObjectName(u"btn_dongzip_reset")
        self.btn_dongzip_reset.setGeometry(QRect(119, 17, 93, 26))
        self.btn_dongzip_reset_2 = QPushButton(self.tab_multi)
        self.btn_dongzip_reset_2.setObjectName(u"btn_dongzip_reset_2")
        self.btn_dongzip_reset_2.setGeometry(QRect(218, 17, 92, 26))
        self.btn_dongzip = QPushButton(self.tab_multi)
        self.btn_dongzip.setObjectName(u"btn_dongzip")
        self.btn_dongzip.setGeometry(QRect(21, 17, 92, 26))
        self.tabWidget.addTab(self.tab_multi, "")
        self.tab_detect = QWidget()
        self.tab_detect.setObjectName(u"tab_detect")
        self.tableView = QTableView(self.tab_detect)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(10, 10, 311, 461))
        self.tabWidget.addTab(self.tab_detect, "")
        self.tab_dongzip = QWidget()
        self.tab_dongzip.setObjectName(u"tab_dongzip")
        self.textBrowser = QTextBrowser(self.tab_dongzip)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(10, 10, 311, 461))
        self.tabWidget.addTab(self.tab_dongzip, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setContextMenuPolicy(Qt.NoContextMenu)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_play.clicked.connect(MainWindow.slot_btn_play)
        self.btn_region_reset.clicked.connect(MainWindow.slot_btn_region_reset)
        self.btn_fileopen.clicked.connect(MainWindow.slot_btn_fileopen)
        self.btn_dongzip_reset.clicked.connect(MainWindow.slot_btn_multi_reset)
        self.btn_dongzip_reset_2.clicked.connect(MainWindow.slot_btn_open_complete)
        self.btn_dongzip.clicked.connect(MainWindow.slot_btn_multi_open)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_region_reset.setText(QCoreApplication.translate("MainWindow", u"\uad00\uc2ec\uc601\uc5ed reset", None))
        self.btn_fileopen.setText(QCoreApplication.translate("MainWindow", u"\ud30c\uc77c\uc5f4\uae30", None))
        self.btn_play.setText(QCoreApplication.translate("MainWindow", u"play", None))
        self.label.setText("")
        self.playTimer.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.btn_init_detection.setText(QCoreApplication.translate("MainWindow", u"\ud0d0\uc9c0\ub0b4\uc5ed \ucd08\uae30\ud654", None))
        self.btn_page_print.setText(QCoreApplication.translate("MainWindow", u"\ud604\uc7ac \ud654\uba74 \uc800\uc7a5", None))
        self.label_fps.setText(QCoreApplication.translate("MainWindow", u"fps", None))
        self.label_roi.setText(QCoreApplication.translate("MainWindow", u"\uad00\uc2ec\uc601\uc5ed", None))
        self.label_xy.setText(QCoreApplication.translate("MainWindow", u"\ud574\uc0c1\ub3c4", None))
        self.label_model.setText(QCoreApplication.translate("MainWindow", u"\ubaa8\ub378", None))
        self.checkbox_move.setText(QCoreApplication.translate("MainWindow", u"\uc6c0\uc9c1\uc784 \uac10\uc9c0 \ud45c\uc2dc", None))
        self.checkbox_yolo.setText(QCoreApplication.translate("MainWindow", u"AI \uac10\uc9c0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\ud504\ub808\uc784 \uac2d", None))
        self.label_thr_yolo.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.label_bright.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\ubc1d\uae30", None))
#if QT_CONFIG(tooltip)
        self.thrSlider_yolo.setToolTip(QCoreApplication.translate("MainWindow", u"\uc815\ud655\ub3c4\ub97c \ub192\uc774\uba74 \uac1d\uccb4 \ud0d0\uc9c0 \uac2f\uc218\ub294 \uc904\uc5b4\ub4ec", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.thrSlider_move.setToolTip(QCoreApplication.translate("MainWindow", u"\uc815\ud655\ub3c4\ub97c \ub192\uc774\uba74 \uac1d\uccb4 \ud0d0\uc9c0 \uac2f\uc218\ub294 \uc904\uc5b4\ub4ec", None))
#endif // QT_CONFIG(tooltip)
        self.label_0.setText(QCoreApplication.translate("MainWindow", u"\uc6c0\uc9c1\uc784 \uac10\ub3c4", None))
        self.label_thr_move.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.label_1.setText(QCoreApplication.translate("MainWindow", u"AI \uac10\ub3c4", None))
        self.label_frame_gap.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_control), QCoreApplication.translate("MainWindow", u"\ucee8\ud2b8\ub864", None))
        self.btn_dongzip_reset.setText(QCoreApplication.translate("MainWindow", u"reset", None))
        self.btn_dongzip_reset_2.setText(QCoreApplication.translate("MainWindow", u"\uc644\ub8cc \uc5f4\uae30", None))
        self.btn_dongzip.setText(QCoreApplication.translate("MainWindow", u"\uba40\ud2f0 open", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_multi), QCoreApplication.translate("MainWindow", u"\uba40\ud2f0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detect), QCoreApplication.translate("MainWindow", u"AI \ud0d0\uc9c0 \ub0b4\uc5ed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_dongzip), QCoreApplication.translate("MainWindow", u"\ub3d9zip \uc548\ub0b4", None))
    # retranslateUi

